fix(zephyr): fix seek whence param parse result
zephyrproject-rtos/lvgl pull request #17
Opened 2022-03-16 07:56 UTC by seasonyuu

### Description of the feature or fix

In Zephyr os, the lvgl fs cannot seek the correct position when the `whence` is not `LV_FS_SEEK_SET`.

### Checkpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Run `code-format.py` from the `scripts` folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [x] Update the documentation

2022-03-16 08:01 UTC, brgl commented
Please add a proper commit message, your sign-off etc. In general try to follow the zephyr's contribution guide where possible.

2022-03-16 08:10 UTC, seasonyuu commented
> Please add a proper commit message, your sign-off etc. In general try to follow the zephyr's contribution guide where possible.

Thanks for your notice. Please review the PR commit, what else should I do?

2022-03-16 08:28 UTC, brgl commented
Is there a compnion PR to the west manifest?

2022-03-16 08:48 UTC, seasonyuu commented
> Is there a compnion PR to the west manifest?

I make a PR there. Please have a look. https://github.com/zephyrproject-rtos/zephyr/pull/43849

2022-03-21 09:38 UTC, brgl commented
@seasonyuu I'm not sure if you saw my comment, can you please add the requested changes? The PR fixes a valid issue so I'd like to merge it.

2022-04-01 02:18 UTC, seasonyuu commented
> @seasonyuu I'm not sure if you saw my comment, can you please add the requested changes? The PR fixes a valid issue so I'd like to merge it.

Sorry that to take so many time to finish it. Now the requested chagned had been done. Please have a look ~

2022-04-06 09:16 UTC, brgl requested changes

2022-04-07 02:33 UTC, seasonyuu commented
Thx for pointing the problem out, I will modify it today

Bartosz Gołaszewski ***@***.***> 于2022年4月6日周三 17:16写道：

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In zephyr/lvgl_fs.c
> <https://github.com/zephyrproject-rtos/lvgl/pull/17#discussion_r827739299>
> :
>
> > @@ -129,7 +129,21 @@ static lv_fs_res_t lvgl_fs_seek(struct _lv_fs_drv_t *drv, void *file,
>  {
>  	int err;
>
> -	err = fs_seek((struct fs_file_t *)file, pos, FS_SEEK_SET);
> +	int fs_whence = FS_SEEK_SET;
>
> Can you define fw_whence above any code and use a switch case for this?
> ------------------------------
>
> In zephyr/lvgl_fs.c
> <https://github.com/zephyrproject-rtos/lvgl/pull/17#discussion_r840345721>
> :
>
> > @@ -128,8 +128,24 @@ static lv_fs_res_t lvgl_fs_seek(struct _lv_fs_drv_t *drv, void *file,
>  				uint32_t pos, lv_fs_whence_t whence)
>  {
>  	int err;
> +	int fs_whence;
>
> Please define this on the same line: int err, fs_whence;
> ------------------------------
>
> In zephyr/lvgl_fs.c
> <https://github.com/zephyrproject-rtos/lvgl/pull/17#discussion_r840346022>
> :
>
> > @@ -128,8 +128,24 @@ static lv_fs_res_t lvgl_fs_seek(struct _lv_fs_drv_t *drv, void *file,
>  				uint32_t pos, lv_fs_whence_t whence)
>  {
>  	int err;
> +	int fs_whence;
> +
> +	switch (whence) {
> +	case LV_FS_SEEK_SET:
> +		fs_whence = FS_SEEK_SET;
> +		break;
> +	case LV_FS_SEEK_END:
> +		fs_whence = FS_SEEK_END;
> +		break;
> +	case LV_FS_SEEK_CUR:
> +		fs_whence = FS_SEEK_CUR;
> +		break;
> +	default:
>
> Just do:
>
> case LV_FS_SEEK_SET:
> default:
>     ...
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/zephyrproject-rtos/lvgl/pull/17#pullrequestreview-911246354>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACB5ARYN6BQKZ6T3NJQPKUDVDVI75ANCNFSM5Q3BFD3Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-04-07 02:40 UTC, seasonyuu commented
By the way, because I rarely contribute to open source projects, I have so
many things to learn. For  example, I use force push to fix those review
codes for now, but I don't know if it is a good way. Is there a better
solution?

Bartosz Gołaszewski ***@***.***> 于2022年4月6日周三 17:16写道：

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In zephyr/lvgl_fs.c
> <https://github.com/zephyrproject-rtos/lvgl/pull/17#discussion_r827739299>
> :
>
> > @@ -129,7 +129,21 @@ static lv_fs_res_t lvgl_fs_seek(struct _lv_fs_drv_t *drv, void *file,
>  {
>  	int err;
>
> -	err = fs_seek((struct fs_file_t *)file, pos, FS_SEEK_SET);
> +	int fs_whence = FS_SEEK_SET;
>
> Can you define fw_whence above any code and use a switch case for this?
> ------------------------------
>
> In zephyr/lvgl_fs.c
> <https://github.com/zephyrproject-rtos/lvgl/pull/17#discussion_r840345721>
> :
>
> > @@ -128,8 +128,24 @@ static lv_fs_res_t lvgl_fs_seek(struct _lv_fs_drv_t *drv, void *file,
>  				uint32_t pos, lv_fs_whence_t whence)
>  {
>  	int err;
> +	int fs_whence;
>
> Please define this on the same line: int err, fs_whence;
> ------------------------------
>
> In zephyr/lvgl_fs.c
> <https://github.com/zephyrproject-rtos/lvgl/pull/17#discussion_r840346022>
> :
>
> > @@ -128,8 +128,24 @@ static lv_fs_res_t lvgl_fs_seek(struct _lv_fs_drv_t *drv, void *file,
>  				uint32_t pos, lv_fs_whence_t whence)
>  {
>  	int err;
> +	int fs_whence;
> +
> +	switch (whence) {
> +	case LV_FS_SEEK_SET:
> +		fs_whence = FS_SEEK_SET;
> +		break;
> +	case LV_FS_SEEK_END:
> +		fs_whence = FS_SEEK_END;
> +		break;
> +	case LV_FS_SEEK_CUR:
> +		fs_whence = FS_SEEK_CUR;
> +		break;
> +	default:
>
> Just do:
>
> case LV_FS_SEEK_SET:
> default:
>     ...
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/zephyrproject-rtos/lvgl/pull/17#pullrequestreview-911246354>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACB5ARYN6BQKZ6T3NJQPKUDVDVI75ANCNFSM5Q3BFD3Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-04-07 07:31 UTC, brgl requested changes

2022-04-07 08:14 UTC, brgl commented
Thanks, now looks good. Please fix your associated zephyr PR.

2022-04-07 08:14 UTC, brgl approved these changes

2022-04-07 10:01 UTC, brgl commented
> By the way, because I rarely contribute to open source projects, I have so many things to learn. For example, I use force push to fix those review codes for now, but I don't know if it is a good way. Is there a better solution? 

No, force push to your development branch is alright.

2022-04-08 09:27 UTC, merged